---
driver:
  name: vagrant
  product_version: 14.1.1

provisioner:
  name: chef_zero
  nodes_path: 'test/fixtures/nodes'
  environments_path: 'test/fixtures/data_bags'
  data_bags_path: 'test/fixtures/data_bags'
  client_rb:
    environment: _default

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[elasticsearch_wrapper_cookbook::default]
    verifier:
      inspec_tests:
        - test/unit/spec
